import { useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { ArrowLeft, Shield, FileText, AlertCircle, Info } from 'lucide-react';

const legalContent = {
  privacy: {
    title: 'Privacy Policy',
    icon: Shield,
    content: [
      {
        heading: 'Data Collection',
        text: 'Gradex, developed by Noskytech, collects minimal data necessary for providing our services. This includes your name, email, academic level, semester, and course information.',
      },
      {
        heading: 'Data Storage',
        text: 'Your academic data is securely stored in our cloud database with encryption. We use industry-standard security measures to protect your information.',
      },
      {
        heading: 'Data Usage',
        text: 'We do not sell, misuse, or share your personal data with third parties. Your data is used solely for calculating your GPA/CGPA and providing personalized academic insights.',
      },
      {
        heading: 'AI Assistant',
        text: 'The Gradex Smart Assistant processes your queries to provide academic guidance. Conversations are handled securely and are not shared with external parties.',
      },
      {
        heading: 'Your Rights',
        text: 'You have the right to access, modify, or delete your data at any time through the app settings. You may also request a complete data export.',
      },
      {
        heading: 'Contact',
        text: 'For privacy-related inquiries, contact us at noskytech1@gmail.com',
      },
    ],
  },
  terms: {
    title: 'Terms of Use',
    icon: FileText,
    content: [
      {
        heading: 'Acceptance',
        text: 'By using Gradex, you agree to these terms of use. If you do not agree, please do not use the application.',
      },
      {
        heading: 'User Responsibilities',
        text: 'You are responsible for entering accurate academic data. Gradex calculates results based on the information you provide.',
      },
      {
        heading: 'Prohibited Activities',
        text: 'You agree not to: reverse-engineer the application, attempt to access other users\' data, use the app for any unlawful purpose, or distribute the app without authorization.',
      },
      {
        heading: 'Intellectual Property',
        text: 'Gradex and all its components are the intellectual property of Noskytech. Unauthorized reproduction or distribution is prohibited.',
      },
      {
        heading: 'Updates',
        text: 'Noskytech may update features, functionality, or these terms at any time. Continued use of the app constitutes acceptance of any changes.',
      },
      {
        heading: 'Termination',
        text: 'We reserve the right to terminate or suspend access to the app for violations of these terms.',
      },
    ],
  },
  disclaimer: {
    title: 'Disclaimer',
    icon: AlertCircle,
    content: [
      {
        heading: 'Calculation Accuracy',
        text: 'GPA and CGPA calculations are based entirely on the data you enter. Results are for guidance only and may not match official academic records.',
      },
      {
        heading: 'No Official Standing',
        text: 'Gradex is not affiliated with any educational institution. Results generated by this app should not be used as official academic documentation.',
      },
      {
        heading: 'Institutional Policies',
        text: 'Noskytech is not responsible for any discrepancies arising from changes in institutional grading policies or calculation methods.',
      },
      {
        heading: 'User Verification',
        text: 'Always verify your results with your institution\'s official academic records. Gradex serves as a tracking and planning tool, not an official grade source.',
      },
      {
        heading: 'Limitation of Liability',
        text: 'Noskytech shall not be held liable for any decisions made based on the results provided by Gradex.',
      },
    ],
  },
  about: {
    title: 'About Gradex',
    icon: Info,
    content: [
      {
        heading: 'Our Mission',
        text: 'Gradex is designed to empower students with tools to track their academic progress, understand their GPA/CGPA, and make informed decisions about their education.',
      },
      {
        heading: 'The 5.0 Grading System',
        text: 'Gradex uses the 5.0 grading scale commonly used in Nigerian universities: A=5.0, B+=4.5, B=4.0, C+=3.5, C=3.0, D+=2.5, D=2.0, F=0.0.',
      },
      {
        heading: 'Features',
        text: 'Calculate semester GPA and cumulative CGPA, track courses across multiple semesters, identify carry-over courses, and get personalized academic insights from our AI assistant.',
      },
      {
        heading: 'The Creator',
        text: 'Gradex is built and powered by Noskytech, a Nigerian tech company focused on creating innovative solutions for students and educational institutions.',
      },
      {
        heading: 'Support',
        text: 'For support, feature requests, or feedback, reach out to us at noskytech1@gmail.com. We\'re always working to improve your experience.',
      },
    ],
  },
};

export default function Legal() {
  const navigate = useNavigate();
  const { page } = useParams<{ page: string }>();
  
  const content = legalContent[page as keyof typeof legalContent];
  
  if (!content) {
    navigate('/dashboard');
    return null;
  }

  const Icon = content.icon;

  return (
    <div className="min-h-screen bg-background pb-20">
      {/* Header */}
      <header className="bg-card border-b border-border sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div className="flex items-center gap-2">
              <Icon className="w-5 h-5 text-primary" />
              <h1 className="text-xl font-bold text-foreground">{content.title}</h1>
            </div>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-2xl mx-auto px-4 py-8">
        <Card className="p-6 space-y-6">
          {content.content.map((section, index) => (
            <div key={index} className="space-y-2">
              <h2 className="text-lg font-semibold text-foreground">{section.heading}</h2>
              <p className="text-muted-foreground leading-relaxed">{section.text}</p>
            </div>
          ))}
        </Card>

        {/* Last Updated */}
        <p className="text-center text-sm text-muted-foreground mt-6">
          Last updated: December 2024
        </p>
      </main>

      {/* Footer */}
      <footer className="fixed bottom-4 left-0 right-0 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-card/80 backdrop-blur-sm border border-border shadow-sm">
          <span className="text-xs text-muted-foreground">Powered by</span>
          <span className="text-sm font-bold bg-gradient-primary bg-clip-text text-transparent">
            NoskyTech
          </span>
        </div>
      </footer>
    </div>
  );
}
